# SERVER
server.port=8080

# NATIVE SECRET IMPORT
# Using 'classpath' works whether you run from the root or the Backend folder.
spring.config.import=optional:classpath:META-INF/secrets.properties

# MONGODB CONFIGURATION (Atlas Connection)
# We use a single URI string to connect to the cloud cluster.
spring.data.mongodb.uri=${MONGODB_URI}



# LOGGING
logging.level.org.springframework.web=INFO

# EMAIL SETTINGS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
