# SERVER
server.port=8080

# NATIVE SECRET IMPORT
# We import from our custom 'secrets' file
spring.config.import=optional:file:src/main/resources/META-INF/secrets.properties

# DATABASE CONFIGURATION (The Map)
# These placeholders pull values from secrets.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# LOGGING
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
